### ISSUE TITLE
TypeError: Cannot call method 'packet' of null

### ISSUE THREAD

**Issue by ecdeveloper** [michetti/socket.io-benchmark#1]
Very often I'm getting the following error (see the stacktrace) when running the benchmark. It could happen even on a small number of users (30-50 users).

TypeError: Cannot call method 'packet' of null
    at Socket.packet (/my/dir/node_modules/socket.io-client/lib/socket.js:290:22)
    at SocketNamespace.packet (/my/dir/node_modules/socket.io-client/lib/namespace.js:64:17)
    at SocketNamespace.emit (/my/dir/node_modules/socket.io-client/lib/namespace.js:113:17)

**Comment by michetti** [comment]
Hi, this project is kind of old already, but I will take a look and maybe update it to the newest versions of node and socket.IO. I was also having some problems with 50 users or so (mostly lost connections)...

Keep in mind that I'm not that experienced with Socket.IO or benchmarks in general, so my implementation is probably not the best one.

**Comment by ecdeveloper** [comment]
ok, thanks :)

**Comment by michetti** [comment]
Hey ecdeveloper, I'm sorry, but I've been very busy these days...
I will probably be able to take a look a this next week...

**Comment by ecdeveloper** [comment]
Ok, great! Still waiting for a new release :)

**Comment by WasserX** [comment]
Hi. I'm not using your project, but doing a benchmark for my app I found the same problem in socket.io-client so I opened an issue there. Maybe it's useful for you too?

https://github.com/LearnBoost/socket.io-client/issues/440
